services:
  db:
    image: mysql:8.0
    container_name: aq_db
    restart: always
    ports:
      - "3300:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - aq_mysql-data:/var/lib/mysql

volumes:
  aq_mysql-data: